email:
  imap_server: imap.gmail.com
  username: your_email@gmail.com
  password: your_app_password
parsing_rules:
  BCA:
    transaction_id: "Número de Documento" 
    client_name: "1º Titular da conta ordenante"
    amount_paid: "Valor do movimento"
    payment_date: "Data-valor"
    bank_reference: "Conta do beneficiário"
    description: "Descritivo do movimento"
notifications:
  webhook:
    url: "https://your-app"
filtering:
  subject_keywords: [""]
  sender_domains: [""]
  fetch_unread_only: true
  time_window_minutes: 60 # Fetch email from the last x minutes
